### PR TITLE
Merge stdlib

### PR DESCRIPTION
**Pull request by adrianvlupu**
Hi,

Apart from changes regarding plantUML compatibility this pull request includes most of the pull requests and issues.
I included @stawirej version of external containers/components. I will add intellij snippets later because the previous vscode snippet file changed a lot.
Queue containers/components have been added by @coryodaniel.

After this merge I can start tagging and checking out the release branch strategy mentioned in the previous discussions.

Edit: actually, there are many more changes: color fixes, arrowheads, deployment and dynamic diagrams, code snippets, bidirectional relationships, sprites, person icon.

### CODE REVIEW

**Review by stawirej — APPROVED** [review]

**Review by IOrlandoni — APPROVED** [review]

**Comment by IOrlandoni** [comment]
@RicardoNiepel Could get your final blessing here?

**Review by artie-groove — APPROVED** [review]
Looks great!

**Comment by adrianvlupu** [comment]
Added one more commit to fix some broken links and to include the relationships from https://github.com/plantuml-stdlib/C4-PlantUML/issues/86 in the readme file.

**Comment by cabello** [comment]
Hello 👋 

Curious about reasoning behind the decision to remove SystemDb and SystemDB_ext in favour of their Container versions.

Thank you for this library 🙇

**Comment by anorm** [comment]
I also wonder about the rationale behind removing `SystemDb` and `SystemDb_Ext`. I've added an issue to get these macros re-introduced.

https://github.com/plantuml-stdlib/C4-PlantUML/issues/113

**Comment by Potherca** [comment]
@anorm Thank you for creating a separate issue for your question!

@marcelstoer and @cabello shall we move this discussion there? :arrow_right: #113

**Pull request merged**
