### PR TITLE
adding person sprite to visualize a Person/Person_Ext, according to the C4 notation

### PR DESCRIPTION
**Pull request by mbajolek**
Sample look and feel of Person and Person_Ext elements:

image

### CODE REVIEW

**Comment by tomByrer** [comment]
Good idea!
But it seems the official C4 Person is more like a rounded rectangle with a ball on top:
image
https://c4model.com/#examples

The icon is another idea, but I would want the icon inside to be 1/2 as big to give more room.

**Comment by mbajolek** [comment]
I've spent some time trying to make it look same as in official notation but failed :) 
It's easy to put image into puml and use it as "component" but you would not be able to embed text inside such thing. 
It's easy to compose "Body" and a "Head" from shapes but you won't have control over where the head is located. That's the beauty or nightmare of puml :)

So, you want the icon to be smaller, correct?

Thanks

**Comment by mbajolek** [comment]
done!

**Comment by Floppy** [comment]
Nice, if we can't get the official shape in, then an icon is helpful.

**Pull request closed without merging**
