### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Potherca**
This is not finished yet, hence this MR is merged as "draft". Feedback on what has already been written is welcome.

The "Release" section is a continuation of the list from #248 

Not to forget:

- [ ] define a ["Release (issue) template"](https://github.com/plantuml-stdlib/C4-PlantUML/issues/templates/edit)

### CODE REVIEW

**Comment by kirchsth** [comment]
Hi @Potherca,

I like the idea.  

What do you think if we directly define a ["Release (issue) template"](https://github.com/plantuml-stdlib/C4-PlantUML/issues/templates/edit) and defined there all checks which should be done. And the constributing.md contains only a reference to the template. 
A generic issue template could be added and referenced too.

Best regards
Helmut

**Comment by kirchsth** [comment]
I found this [CONTRIBUTING.md](https://github.com/actions/python-versions/blob/main/CONTRIBUTING.md) and the corresponding [CODE_OF_CONDUCT.md](https://github.com/actions/python-versions/blob/main/CODE_OF_CONDUCT.md) and other links, ...

It contains a lot of guidelines, e.g "Write [good commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)". Or it contains a description of the folder structure, ....

**Comment by Potherca** [comment]
In my experience it helpt to have both the prose in the `CONTRIBUTING.md` and the template, but yes, I was also thinking about issue templates!

I don't like the defaults GitHub offers, so I was thinking about defining what it is we want first, and then creating templates from that.

**Comment by kirchsth** [comment]
I see you have much more experiences in this area than I have. You are right we should start with smaller steps.

Related to the commit messages, I only saw it and thought it is a very complete description which covers nearly everything. Personally I'm happy if I can check in some files into git (without deleting other local files during a merge process ;-) )

**Comment by Potherca** [comment]
> Personally I'm happy if I can check in some files into git (without deleting other local files during a merge process)

Yeah, I keep coming back to this:

> Git may be simple but it is not *easy*.
>
> The highest voted questions on StackOverflow:
>
> - Top 3: 60% git
> - Top 10: 50% git
> - Top 25: 40% git
> [image](https://twitter.com/potherca/status/1526874089947811842)

With the other almost 40%[^1] of the Top 25 (marked blue) is taken up by javascript and JSON.

[^1]: 36% to be precise

**Comment by kirchsth** [comment]
cleanup stalled pull request.
If still a concrete solution is planed please reopen it or create a new issue/pull-request.

**Pull request closed without merging**
