### PR TITLE
Add dotted relationships arrows

### PR DESCRIPTION
**Pull request by fineconstant**
Hello,

An option to make relationship arrows dotted would be very useful to express different types of relationships and distinguish them visually 😃 

For now I named new elements using `_Async` suffix e.g. `Rel_Async(...)`, but maybe it is better not to suggest that these new relationships are asynchronous and normal ones are synchronous... in the end it can mean something different based the context.
Other names like `_Weak`, `_Dotted` or something entirely else are possible - feel free to comment on this or suggest something 😄

### CODE REVIEW

**Comment by Floppy** [comment]
I like it, but the naming would be better as `_Dotted` or similar, rather than adding specific semantics which aren't specified by C4.

**Comment by kamilduda** [comment]
@Floppy Thanks for feedback, I'll rename it to `_Dotted` as I don't have any better idea 😄

**Comment by jikuja** [comment]
Actually, Brown's book is suggesting using dashed arrows for async communications.

> As with elements, you can use different line styles and colour to add an additional level of information to your diagram. For example, perhaps synchronous interactions are illustrated using solid lines, whereas asynchronous interactions are illustrated using dashed lines.

The choice of the function name is semantics and the book has another even more important point for different arrow styles:

> Once again, ensure that any styling supplements the existing information wherever possible and that the styles you use are described on the key/legend.

If multiple arrow styles are used it should be easy to add description to arrows and automatically add them into legend.

**Review by Potherca — APPROVED** [review]

**Comment by kirchsth** [comment]
@fineconstant, @Potherca: #67 is already closed,  can we close this issue based on #130 too?

**Comment by fineconstant** [comment]
Close based on #130

**Comment by kirchsth** [comment]
With #160 dotted lines are supported too

**Pull request closed without merging**
