### PR TITLE
#27 Add deployment and dynamic diagrams support

### PR DESCRIPTION
**Pull request by kirchsth**
I'm extending the Structurizr.Net with an new PlantUML writer with dynamic and deployment view support. During that I added the 2 diagrams definitions. If you want you could pull it.
I added the definitions, samples and updated the readme.  

**please update all raw references to the correct one during merge from 
https://raw.githubusercontent.com/kirchsth/C4-PlantUML/master/...
to
https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/... ***

### CODE REVIEW

**Comment by adrianvlupu** [comment]
Hi,
While I think it's a good idea to add deployment elements, I don't really agree with the implementation. 
The only difference between a **Deployment_Node** and a general **Boundary** is the solid border and the black font color.
The **ContainerInstance** should just be a **Container**.
This way, the diagrams would better resemble the ones in the C4Model docs.

A better implementation would be to add a new skinparam

```puml
skinparam rectangle<<node>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor #000000
    BorderColor #000000
    BorderStyle solid
}
```

and new Node element

```puml
!define Node(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<node>> as e_alias
```

The `C4_Dynamic.puml` seems to serve no purpose. I think new `puml` files should be added only if they add new elements.

**Comment by kirchsth** [comment]
My main intention was to extend structurizr/dotnet with a new C4PlantUmlWriter which creates similar diagrams like structurizr itself (the [test_writeBigBankPlcWorkspace()](https://github.com/kirchsth/dotnet/blob/master/Structurizr.PlantUML.Tests/IO/C4PlantUML/C4PlantUmlWriterTests.cs) test produces the different diagrams – if you want to see them replace the 2 "" with one ") and with my “C4-PlantUML” merge request I only want to synchronize the generated diagrams.

at DeploymentNode, ContainerInstance) all terms are already used in the structurizr model therefore I “reused” it them as Deployment_Node and ContainerInstance (I cannot use container, because term container is already used and has a different meaning in the model).

at DeploymentNode, Boundary) the C4 diagrams use already 3 different boundaries and a node is not a boundary. Additional structurizr uses round corners in the diagrams and I want to produce the same layout (e.g. round corners) too. And a container is not an instance therefore I added the round corners to the instances too.
(colors and shadows are a matter of taste but none of the boundary colors was black in the other diagrams)

at Deployment_Node) I reused only the same pattern like all boundary Container_Boundary, Enterprise_Boundary ... but Node itself is fine too

at C4_Dynamic.puml) basically you are right, but I want to decouple the writer and C4-diagram definitions and introduced the C4_Dynamic.puml too that each diagram type has its own *puml file (e.g. it could be that different legends are introduced,…)

at C4.code-snippets) can you extend it? I generate the diagrams with structurizr/dotnet and use no code snippets

**Comment by kirchsth** [comment]
@adrianvlupu can you check my changes in my branch before I make a new pull request? C4.code-snippets are in work. I will finish it as soon your check is ok.

**Comment by kirchsth** [comment]
Hi @adrianvlupu, @RicardoNiepel all my changes are in:
- Deployment.puml has a new Node, 
- Dynamic.puml has a new Interact and Interact2 == Rel with automatic numbering,
- Updated C4 code snippets
- fix missing LAYOUT_WITH_LEGEND... () in images and documentation

I hope you like it, I used the changes already in the new  [structurizr-C4PlantUmlWriter](https://github.com/structurizr/dotnet/pull/52)

Best regards
Helmut

PS.: It still contains links to my git repository, please update/remove them as soon you accept my changes

**Comment by adrianvlupu** [comment]
Hi @kirchsth,

I like how you handled the `$index` for the dynamic diagrams. I took your example of both deployment and dynamic diagrams and added them to my repository with some changes.

Because I updated my version a while back to use plantuml 1.2019.6, I couldn't merge your version directly. I also changed `Interact` and `Interact2` to `Rel` (override) and `RelIndex` just for the sake of simplicity.

👍 Just wanted to thank you for the contribution and I wish you a happy holiday season 🎄

**Comment by surmen92** [comment]
What is needed to merge this pull request? If nothing, could we merge this branch as soon as possible?

**Comment by b0ric** [comment]
Would be really great to see this merged.

**Comment by prathik** [comment]
@RicardoNiepel could we get this merged, feature is useful

**Comment by NJ-Brad** [comment]
There were several changes required, in order to work with the new preprocessor.  I have made the required changes, and incorporated many of the pull requests into my fork of this great project.  https://github.com/NJ-Brad/C4-PlantUML  I am working on several projects and wanted to utilize these improvements.

**Comment by kirchsth** [comment]
@adrianvlupu merged my changes already via a different PR, therefore I close my PR

**Pull request closed without merging**
