### PR TITLE
Show persons as "Awesome" Actor instead of box.

### PR DESCRIPTION
**Pull request by joodie**
test
Renders Person and Person_Ext using portrait outline instead of a
rectangle. This makes human actors stand out much clearer in the
diagrams.

This uses the apparently new and undocumented "ActorStyle AWESOME"
skinparam. It will fall back to stick figures on older PlantUML
versions. I'm not sure if there's a way to make it fall back to older
behaviour (rendering rectangles).

### CODE REVIEW

**Comment by adrianvlupu** [comment]
This looks awesome !

**Comment by joodie** [comment]
@adrianvlupu thanks! If there's anything I can do to improve the quality of the code or otherwise speed up the process of accepting the PR, please let me know!

**Comment by mdopp** [comment]
@joodie first of all => Cool!
You removed the EOF character, this is distracting a little from the functional change.

**Comment by joodie** [comment]
@mdopp oops sorry about that. My Emacs settings added those newlines automatically. I removed the newlines.

**Comment by ncasaux** [comment]
Hello,
I like the idea, however it seems to me that it prevents to put some description on the person.
I would prefer to have a "real" rectangle (like currently) with a circle on top as a head ;)

**Comment by joodie** [comment]
@ncasaux I would like to have something even closer to the diagrams on https://c4model.com/ but PlantUML doesn't really allow for that. The Person icon I've used here was (recently) added to the built-in PlantUML graphics set and you can't really tweak it it in a diagram file.

**Comment by ncasaux** [comment]
@joodie I agree... Unfortunatey, I don't have any suggestion to achieve this (if it's possible...)

**Comment by ncasaux** [comment]
I just saw this other option to draw a proper person, which seems quite interesting:
https://github.com/RicardoNiepel/C4-PlantUML/pull/58

**Comment by roxspring** [comment]
> I like the idea, however it seems to me that it prevents to put some description on the person.

Correct, PlantUML doesn't allow text to be placed within the actor symbol, but text can be placed below so it's still possible to have the description present.

> I would prefer to have a "real" rectangle (like currently) with a circle on top as a head ;)

Sure, it'd be nice to render it just like the official C4 model but getting that out of PlantUML will be a struggle.
Personally I like this solution - but then I contributed the awesome actor symbol to PlantUML so am biased.
Ultimately I think this or #58 would be a massive improvement on the current plain rectangle.

**Comment by aheil** [comment]
It looks like we have a couple of issues addressing this. Actually this one seems to be one that aligned quite well with the "official" C4 notation. Also it seems to be minimal invasive in terms of the code based. I would vote to go for this solution.

**Comment by Potherca** [comment]
If we can confirm that this MR does conflict in logic with anything that has been merged up to now, I think this can be merged.

**Review by Potherca — APPROVED** [review]

**Comment by Berkmann18** [comment]
That would make diagrams clearer.

**Comment by kirchsth** [comment]
A possible new concept could be 
```
...
!$COLOR_A_5 = "#7f3b08"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
UpdateSkinparamsAndLegendEntry("person", $bgColor=$COLOR_A_5, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_A_1, $shadowing="true")

SHOW_PERSON_AWESOM() ' internal it calls HIDE_PERSON_SPRITE and activate actor, and font color uses background color 

AddProperty("Name", "Flash")
AddProperty("Organization", "Zootopia")
AddProperty("Tool", "Internet Explorer 7.0")
Person(personAlias, "Label", "Optional Description (with default property header)")

Person(simplePerson, "Simple Person")

' and if a sprite is defined, rectangles are used like before
Person(simplePersonWithSprite, "Simple Person", $sprite="person2")
...
```



compare it with (uncolored) https://github.com/plantuml-stdlib/C4-PlantUML#element-properties

**Comment by kirchsth** [comment]
I would replaced this PR with PR #140 that we can support all existing $tag, property, ... features too

**Comment by Potherca** [comment]
@joodie I hope you do not mind, but I think we might want to close this MR in favor of the implementation in https://github.com/plantuml-stdlib/C4-PlantUML/pull/141...

**Comment by Potherca** [comment]
Closing in favour of #141

**Pull request closed without merging**
