### PR TITLE
Add live templates for IntelliJ

### PR DESCRIPTION
**Pull request by stawirej**
IntelliJ Live Template for supporting creation of C4 model diagrams with C4-PlantUML.

### CODE REVIEW

**Comment by Potherca** [comment]
This seems like a nice addition but I am hesitant about added that zip file to this repo... Especially as that would then also mean we would need to maintain it... I think this MR would be more feasible if the templates zaip could be gotten from elsewhere...

**Comment by adrianvlupu** [comment]
I think we can handle a zip file if that is the format intellij wants. Snippets need to be updated though. I'm willing to do that, already checked his branch of C4-PlantUML with the feature. Let's merge this and update it after https://github.com/plantuml-stdlib/C4-PlantUML/pull/84

**Comment by stawirej** [comment]
As @adrianvlupu said, I would merge it and update later to reflect latest changes. Zip file is standard way how IntelliJ handles live templates.

**Review by Potherca — APPROVED** [review]

**Review by Potherca — COMMENTED** [review]
The zip file contains a `_MACOS` folder that I don't think is needed?

**Pull request merged**
