### PR TITLE
#119, #72: All elements and relationships can support hyperlinks (based on #126)

### PR DESCRIPTION
**Pull request by kirchsth**
Hi,

I created a new PR based on #126 with link support. It should cover #119 and #72.
I didn't merge the links support into #126 that the link extensions can be rejected.

I extended all calls with a $links="..." that all elements and relationships can have a link like below

```csharp
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

Person(admin, "Administrator", $sprite="person2", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_person_sprite-or-show_person_spritesprite")
System_Boundary(c1, "Sample System", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}
System(twitter, "Twitter", $link="https://github.com/plantuml-stdlib/C4-PlantUML")

Rel(admin, web_app, "Uses", "HTTPS", $link="https://plantuml.com/link")
Rel(web_app, twitter, "Gets tweets from", "HTTPS", $link="https://plantuml.com/link")
@enduml
```

> `png` itself supports no links, therefore the following image is generated as `svg` image.
> Github does not support `svg` links in Markdown.
> If you click on the image a new window is opened and there you can use the links.

Click on the image that the links are working

The implementation can be checked via my [extended](https://github.com/kirchsth/C4-PlantUML/tree/extended) branch

BR Helmut

### CODE REVIEW

**Review by Potherca — APPROVED** [review]
The code changes look good. I haven't checked the www.plantuml.com/plantuml/ diagrams this time, though.

**Comment by kirchsth** [comment]
@Potherca: on plantuml server it is working (it overlays png with maps, details see end of #72).

**Comment by adrianvlupu** [comment]
Considering the changes, I think a new version needs to be released before merging this

**Review by adrianvlupu — APPROVED** [review]

**Comment by Potherca** [comment]
@adrianvlupu I've taken the liberty of tagging [v2.1.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.1.0). (and supplying milestones for all MRs/issues) Do you think we should also create a release branch? (As was done with v2.0.0, since files now link to `master`).

**Comment by kirchsth** [comment]
@Potherca thank you for Release 2.1. Can you please release v 2.2 soon too?
 (#126 contains changes following changes and therefore I think 2.1 should be a "short living" release:
    UpdateSkinparamsAndLegendEntry -> UpdateElementStyle
    SHOW_DYNAMIC_LEGEND -> SHOW_LEGEND 
)

**Comment by Potherca** [comment]
@kirchsth Release is planned for my FOSS work this weekend.

**Comment by Potherca** [comment]
@kirchsth This has been released as [v2.2.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.2.0).

Before tagging the release, I did add https://github.com/plantuml-stdlib/C4-PlantUML/commit/621a191552ff5b9a3e844e9353588e3c56a04432 to make sure that `master` doesn't break because of `SHOW_DYNAMIC_LEGEND` being renamed. (This would have effectively meant a v3 release as it breaks backward compatibility). For future MRs this might be something to take into account, as we want to break `master` as little as we possibly can.

I would have liked to add more to that release but, because of 2 reviewers being needed, things will have to wait for `v2.3` . :disappointed:

**Comment by kirchsth** [comment]
@Potherca thank you for the extension, deprecated is a good idea

**Pull request merged**
