### PR TITLE
Allow use of collections in c4 diagrams

### PR DESCRIPTION
**Pull request by jlesueur**
Currently, there is no way to create a collection in either context or container level. Here is an example showing how a RBAC permission system can work:

image

### CODE REVIEW

**Comment by kirchsth** [comment]
Hi @jlesueur,

thank you for your suggestion, but I'm really not sure if we should add a new shape to the standard,
because it would requires also 6 additional Element calls (SystemCollection, SystemCollection_Ext, ContainerCollection, ContainerCollection_Ext, ComponentCollection, ComponentCollection_Ext), a detailed discussion can found [Support more Shapes](https://github.com/plantuml-stdlib/C4-PlantUML/issues/145).
@Potherca  what do you think?

Personally I would suggest $shadowing=true or a specific color as collection marker, but of course you could use a specific $sprite=... for that too.

[](http://www.plantuml.com/plantuml/uml/bP71RXCn48RlVWgpuh0LeK6Xt5ZK428u840jYEDgufqc9hPdvR5LAiIxuzswsQoqAUh9oVpVVAFykUG0FaHhX7YcdJAnGVbsTJ5VNTGhiYqvTE6yJVcxOo345Xh_Udv3Bho4MsIoE8-CdZCxe1O2UWrchdQezXlwNTjeWcuDrXi3RbzJ34OxVChED0k-uS4cnB9frWOjkl0TjcNne2XcyZdleA5RxRPL4NpiHvljYWpvocDprk_cdv-tqwl3NN5sAf6AZ44LDBaJ1xZrEc1LMAZ_KyMC5HYiNfqltgI3uXjw9bToiXdymUXdibZAhksKvZ2B7k8kvAEZUJ29Bp8l5zr2W2rNGrVfl7XFqJNWxygM4veCLZDhSiad_mXnQADi3z686xI74eSTJmOxxLNtZibngQCbPARe5Gv7UWVUJ-NH-D7ZqAl7acK_cr8CjRoOS77S_48Lak7w_jF4vRz2NA4P_PEZpe3tgTIUoQUUG2sciPux3lh6Sovlo4i4jSk-d9teTmSyvd9_ZqD3CGgSPCGKY-jFNt_MdzSVrry-bEdh9RecMlCF)

If you still want your additional shape you could define it based on [following pattern](https://github.com/plantuml-stdlib/C4-PlantUML/issues/145#issuecomment-830615476). It should (basically) work, maybe there are some minor changes required in the meantime. 

Best regards
Helmut

PS.: In your solution the definition of the ComponentCollection(), ... procedures is missing. Did you added all files to the commit?

**Comment by kirchsth** [comment]
I fixed the sample and fill the missing $shape with "".

[](http://www.plantuml.com/plantuml/uml/pLRlRzis4Fskl-AYUPWDf7QpR2qm840zHsq3E7PWE_lnIQ2biqsK4bMIIfmD-zztb2o2RXNKK36i_cBgIBvtx_6aunjjc39b9e8V897v0oe3tC0ZDpjWQSeDbpaJD9LbB4z1y1o1gMsPOMxWnVKYcevNDxz5ySriChs_Zgx2OGX6GgaHX4oO44_16T_0zmzCSROM6EEUQwFxuQSxmq40SCRpH9Gfmd0q78ucFyKJcHKo9wvXONCyGw7HNxSpfj2_Z4QAFGwtb7Ev9cP5GepTGrcF2i5og--5DgdWQm9zSMT3zxVJKSQqGTNAawTy4v0dLy__x7IA6-k8xnHfri5PcNyifS4K2YKJJ4k5S5-apE1xtBEjp9VcIU1AodxFiEsIia1v3htrTYA5L5TXI0yRKk4zhgLAKNa1lMEfVEJvbXu7GGy5saDP4Tm7dXTCiOnitjLqjBwDo6Svfl3npu48Aa-Sc21ebRXy8aEpWyH-ZmdED249jaP1_odgf4c-KDmWZUl4T3sYylfGgJca3M5lYwP6xH_3E8o1NNAdPA7xWv30P2sIjEjgNyCm0AQXJWdibYbnzIl6JxLzKLaSxSt_hWxtDCgPYBlAfF9L-B7a2ZLKhq1k61MpQjNlPfyzN8F9BkzkWoFejoEUu4ZIG7G_ydR9_gb_Ux9T8JZzNrqBxdFOQeoR_QzgmH5yHIqq4E5vzr9eL-nAuTjJxKgXktog18t6DZPM2WFQzYaDWMvw2ZGv_nq0_MfgyrJWMwg-9VyBuUB7QiQr3zWmsxN_2OBs3kXzfvT_BbVHRVphktWodyuN58ccqMqqMyLlvxDL4tJBvelhQD54AvP1EqVhrpBwOnKjPkDfV2AhMz-1_kZLd13g-6P6Uxz4wLPsq-gnUkcVJk-sTCl35M4j-lPkFYCAdzK5VLu_t56su_Krd9v0owRsJEm5iSlFRkGRI4fjP7PunpGmXSrNEAtkaVwzijUkcbxVNfLJF8v_XYi8ltkzkLnlNeTU_AAAR_3bIpy-Y-vNY_6qcdlrwlBIpjKSKNsJh3YwsUeoyiONtS-lAz71PfRxHYQbzTomBN3jx0Qpmxps_1cVmKWPZDCqSjViVgWBJ3WJeNTpFpRt6QqdxGo2p-vSYHSuXt1PWu1R5rAmQXaqQ2ZW0PKcvQu3EMwY-AoJM-jhyCEKESAS5mSJhsr3ujKJuRIrnmQAXhJHhO1exq5QbSltyz_ZQVGkcbttm-hWAFm6yxJCnBy0)

**Comment by jlesueur** [comment]
Hi @kirchsth,

Yeah, I didn't include the ContainerCollection code, as I was just aiming at adding support so that it could be added as a custom thing, not part of the framework. Of course, I'm not opinionated about that. Those suggestions (shadowing and a sprite), seem pretty good too. Thanks for pointing me to the other discussion.

**Comment by kirchsth** [comment]
Similar like #145, additional shapes can be added with a custom include file (details see above)

**Pull request closed without merging**
